title: Yet Another Wiki
author: Yue Wu
imgbase: "/assets/images"

remote_theme: pmarsceill/just-the-docs
color_scheme: light
permalink: pretty
exclude: ["README.md"]

search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
footer_content: "Copyright &copy; 2017-2021 Yue Wu."
